// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {guiapi} from '../models';
import {main} from '../models';

export function AdvanceOrientation():Promise<guiapi.DiagOutcome>;

export function AdvanceTutorial(arg1:number,arg2:number):Promise<guiapi.TutorialPos>;

export function CheckLang(arg1:string):Promise<guiapi.LangStatus>;

export function DeleteProfile(arg1:string):Promise<string>;

export function GetAdvancedTopic(arg1:string,arg2:number):Promise<guiapi.AdvTopicDetail>;

export function GetAdvancedTopics(arg1:string):Promise<Array<guiapi.AdvTopicSummary>>;

export function GetGate(arg1:string):Promise<guiapi.GateView>;

export function GetHintInfo(arg1:string,arg2:string):Promise<guiapi.HintInfo>;

export function GetInstallGuide(arg1:string):Promise<guiapi.InstallGuideView>;

export function GetLangPresence():Promise<Array<guiapi.LangStatus>>;

export function GetLanguages():Promise<Array<guiapi.LangInfo>>;

export function GetLesson(arg1:number):Promise<guiapi.LessonView>;

export function GetMentorBackends():Promise<Array<main.MentorStatusView>>;

export function GetMentorPreview(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function GetPrimer(arg1:string,arg2:string):Promise<guiapi.PrimerView>;

export function GetProblem(arg1:string,arg2:string):Promise<guiapi.ProblemDetail>;

export function GetProfiles():Promise<Array<guiapi.ProfileView>>;

export function GetProgress(arg1:string):Promise<guiapi.Progress>;

export function GetVersion():Promise<string>;

export function GetWallet(arg1:string):Promise<guiapi.WalletView>;

export function GetWriteup(arg1:string,arg2:string):Promise<guiapi.WriteupView>;

export function Grade(arg1:string,arg2:string,arg3:string):Promise<guiapi.GradeResult>;

export function GradeAdvanced(arg1:string,arg2:number,arg3:number,arg4:string):Promise<guiapi.GradeResult>;

export function GradeLessonStage(arg1:number,arg2:number,arg3:string):Promise<guiapi.GradeResult>;

export function GradedLanguages():Promise<Array<string>>;

export function ListProblems(arg1:string):Promise<Array<guiapi.ProblemSummary>>;

export function NextProblem(arg1:string,arg2:string):Promise<string>;

export function ProbeMentor(arg1:string):Promise<string>;

export function RecheckLang(arg1:string):Promise<guiapi.LangStatus>;

export function RequestHint(arg1:string,arg2:string,arg3:number,arg4:string):Promise<guiapi.HintResult>;

export function ResumeTutorial():Promise<guiapi.TutorialPos>;

export function SelectMentor(arg1:string):Promise<string>;

export function SetMentorEndpoint(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartDevLiteracy():Promise<guiapi.DevLitStep>;

export function StartOrientation(arg1:string,arg2:string):Promise<guiapi.OrientationStep>;

export function StartTutorial(arg1:string):Promise<number>;

export function SubmitDevCommand(arg1:string):Promise<guiapi.DevLitOutcome>;

export function SubmitOrientationChoice(arg1:number):Promise<guiapi.DiagOutcome>;

export function SubmitOrientationCode(arg1:string):Promise<guiapi.DiagOutcome>;

export function SubmitOrientationSpec(arg1:string):Promise<guiapi.DiagOutcome>;

export function SubmitWriteup(arg1:string,arg2:string,arg3:number,arg4:string):Promise<guiapi.WriteupResult>;
