// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvanceOrientation() {
  return window['go']['main']['App']['AdvanceOrientation']();
}

export function AdvanceTutorial(arg1, arg2) {
  return window['go']['main']['App']['AdvanceTutorial'](arg1, arg2);
}

export function CheckLang(arg1) {
  return window['go']['main']['App']['CheckLang'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetAdvancedTopic(arg1, arg2) {
  return window['go']['main']['App']['GetAdvancedTopic'](arg1, arg2);
}

export function GetAdvancedTopics(arg1) {
  return window['go']['main']['App']['GetAdvancedTopics'](arg1);
}

export function GetGate(arg1) {
  return window['go']['main']['App']['GetGate'](arg1);
}

export function GetHintInfo(arg1, arg2) {
  return window['go']['main']['App']['GetHintInfo'](arg1, arg2);
}

export function GetInstallGuide(arg1) {
  return window['go']['main']['App']['GetInstallGuide'](arg1);
}

export function GetLangPresence() {
  return window['go']['main']['App']['GetLangPresence']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetLesson(arg1) {
  return window['go']['main']['App']['GetLesson'](arg1);
}

export function GetMentorBackends() {
  return window['go']['main']['App']['GetMentorBackends']();
}

export function GetMentorPreview(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMentorPreview'](arg1, arg2, arg3, arg4);
}

export function GetPrimer(arg1, arg2) {
  return window['go']['main']['App']['GetPrimer'](arg1, arg2);
}

export function GetProblem(arg1, arg2) {
  return window['go']['main']['App']['GetProblem'](arg1, arg2);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetProgress(arg1) {
  return window['go']['main']['App']['GetProgress'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWallet(arg1) {
  return window['go']['main']['App']['GetWallet'](arg1);
}

export function GetWriteup(arg1, arg2) {
  return window['go']['main']['App']['GetWriteup'](arg1, arg2);
}

export function Grade(arg1, arg2, arg3) {
  return window['go']['main']['App']['Grade'](arg1, arg2, arg3);
}

export function GradeAdvanced(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GradeAdvanced'](arg1, arg2, arg3, arg4);
}

export function GradeLessonStage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GradeLessonStage'](arg1, arg2, arg3);
}

export function GradedLanguages() {
  return window['go']['main']['App']['GradedLanguages']();
}

export function ListProblems(arg1) {
  return window['go']['main']['App']['ListProblems'](arg1);
}

export function NextProblem(arg1, arg2) {
  return window['go']['main']['App']['NextProblem'](arg1, arg2);
}

export function ProbeMentor(arg1) {
  return window['go']['main']['App']['ProbeMentor'](arg1);
}

export function RecheckLang(arg1) {
  return window['go']['main']['App']['RecheckLang'](arg1);
}

export function RequestHint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RequestHint'](arg1, arg2, arg3, arg4);
}

export function ResumeTutorial() {
  return window['go']['main']['App']['ResumeTutorial']();
}

export function SelectMentor(arg1) {
  return window['go']['main']['App']['SelectMentor'](arg1);
}

export function SetMentorEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMentorEndpoint'](arg1, arg2, arg3);
}

export function StartDevLiteracy() {
  return window['go']['main']['App']['StartDevLiteracy']();
}

export function StartOrientation(arg1, arg2) {
  return window['go']['main']['App']['StartOrientation'](arg1, arg2);
}

export function StartTutorial(arg1) {
  return window['go']['main']['App']['StartTutorial'](arg1);
}

export function SubmitDevCommand(arg1) {
  return window['go']['main']['App']['SubmitDevCommand'](arg1);
}

export function SubmitOrientationChoice(arg1) {
  return window['go']['main']['App']['SubmitOrientationChoice'](arg1);
}

export function SubmitOrientationCode(arg1) {
  return window['go']['main']['App']['SubmitOrientationCode'](arg1);
}

export function SubmitOrientationSpec(arg1) {
  return window['go']['main']['App']['SubmitOrientationSpec'](arg1);
}

export function SubmitWriteup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitWriteup'](arg1, arg2, arg3, arg4);
}
